version: "3.8"

services:
  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    restart: always
  web:
    build: .
    command: bash -c "python /usr/src/server_agent/manage.py migrate --noinput &&
            python /usr/src/server_agent/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/server_agent
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: