# Generated by Django 3.1.4 on 2020-12-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FileClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.FileField(upload_to='')),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('numbers', models.ManyToManyField(to='upload.Number')),
            ],
        ),
    ]
